export enum BookingIntent {
  UNKNOWN = 'UNKNOWN',
  GREETING = 'GREETING',
  PROVIDE_SERVICE = 'PROVIDE_SERVICE',
  PROVIDE_DATE = 'PROVIDE_DATE',
  PROVIDE_TIME = 'PROVIDE_TIME',
  CONFIRM_BOOKING = 'CONFIRM_BOOKING',
  CANCEL_BOOKING = 'CANCEL_BOOKING',
}
